 analyzer:
   plugins:
     - dart_code_metrics

 dart_code_metrics:
   metrics:
     cyclomatic-complexity: 20
     number-of-arguments: 4
   metrics-exclude:
     - test/**
   rules:
     - newline-before-return
     - no-boolean-literal-compare
     - no-empty-block
     - prefer-trailing-comma-for-collection